package gui.tools;

import abc.套装系统完善版;
import database.DatabaseConnection;
import gui.HuiMS;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author 小灰灰
 */
public class 套装系统 extends javax.swing.JFrame {

    /**
     * Creates new form 套装系统
     */
    public 套装系统() {
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("image2/logo.png"));
        setIconImage(icon.getImage());
        setTitle("套装系统管理控制台");
        initComponents();
        initview();//初始化控件信息
        HuiMS.GetConfigValues();
        刷新套装叠加开关();
        刷新套装系统开关();
        刷新套装1最少触发件数();
        刷新套装1附加百分比伤害();
        刷新套装1多穿一件附加();
        刷新套装2最少触发件数();
        刷新套装2附加百分比伤害();
        刷新套装2多穿一件附加();
        刷新套装3最少触发件数();
        刷新套装3附加百分比伤害();
        刷新套装3多穿一件附加();
        刷新套装4最少触发件数();
        刷新套装4附加百分比伤害();
        刷新套装4多穿一件附加();
        刷新套装5最少触发件数();
        刷新套装5附加百分比伤害();
        刷新套装5多穿一件附加();
        刷新套装6最少触发件数();
        刷新套装6附加百分比伤害();
        刷新套装6多穿一件附加();
        刷新所有套装装备();
    }
    public void initview() {
        ((JPanel) getContentPane()).setOpaque(true); // 将JFrame上自带的面板设置为透明，否则背景图片
        UIManager.put("TabbedPane.contentOpaque", true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel47 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        套装1触发件数 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        套装1伤害增加百分比 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        套装1多穿一件增加 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        套装1装备 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        套装2触发件数 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        套装2装备 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        套装2伤害增加百分比 = new javax.swing.JTextField();
        套装2多穿一件增加 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        套装3触发件数 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        套装3装备 = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        套装3伤害增加百分比 = new javax.swing.JTextField();
        套装3多穿一件增加 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        套装4触发件数 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        套装4装备 = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        套装4伤害增加百分比 = new javax.swing.JTextField();
        套装4多穿一件增加 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        套装5触发件数 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        套装5装备 = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        套装5伤害增加百分比 = new javax.swing.JTextField();
        套装5多穿一件增加 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        套装6触发件数 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        套装6装备 = new javax.swing.JTextArea();
        jLabel51 = new javax.swing.JLabel();
        套装6伤害增加百分比 = new javax.swing.JTextField();
        套装6多穿一件增加 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        套装叠加 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        套装系统 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel47.setEnabled(false);

        jLabel10.setText("套装1套装最低触发件数：");

        套装1触发件数.setText("0");
        套装1触发件数.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装1触发件数ActionPerformed(evt);
            }
        });

        jLabel11.setText("伤害附加/百分比：");

        套装1伤害增加百分比.setText("0");
        套装1伤害增加百分比.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装1伤害增加百分比ActionPerformed(evt);
            }
        });

        jLabel12.setText("套装1装备：");

        jLabel22.setText("多穿一件/百分比：");

        套装1多穿一件增加.setText("0");
        套装1多穿一件增加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装1多穿一件增加ActionPerformed(evt);
            }
        });

        套装1装备.setColumns(20);
        套装1装备.setLineWrap(true);
        套装1装备.setRows(5);
        jScrollPane3.setViewportView(套装1装备);

        jLabel25.setText("套装2套装最低触发件数：");

        套装2触发件数.setText("0");
        套装2触发件数.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装2触发件数ActionPerformed(evt);
            }
        });

        jLabel28.setText("套装2装备：");

        套装2装备.setColumns(20);
        套装2装备.setLineWrap(true);
        套装2装备.setRows(5);
        jScrollPane4.setViewportView(套装2装备);

        jLabel29.setText("伤害附加/百分比：");

        套装2伤害增加百分比.setText("0");
        套装2伤害增加百分比.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装2伤害增加百分比ActionPerformed(evt);
            }
        });

        套装2多穿一件增加.setText("0");
        套装2多穿一件增加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装2多穿一件增加ActionPerformed(evt);
            }
        });

        jLabel30.setText("多穿一件/百分比：");

        jLabel31.setText("套装3套装最低触发件数：");

        套装3触发件数.setText("0");
        套装3触发件数.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装3触发件数ActionPerformed(evt);
            }
        });

        jLabel32.setText("套装3装备：");

        套装3装备.setColumns(20);
        套装3装备.setLineWrap(true);
        套装3装备.setRows(5);
        套装3装备.setToolTipText("");
        jScrollPane6.setViewportView(套装3装备);

        jLabel33.setText("伤害附加/百分比：");

        套装3伤害增加百分比.setText("0");
        套装3伤害增加百分比.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装3伤害增加百分比ActionPerformed(evt);
            }
        });

        套装3多穿一件增加.setText("0");
        套装3多穿一件增加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装3多穿一件增加ActionPerformed(evt);
            }
        });

        jLabel34.setText("多穿一件/百分比：");

        jLabel36.setText("套装4套装最低触发件数：");

        套装4触发件数.setText("0");
        套装4触发件数.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装4触发件数ActionPerformed(evt);
            }
        });

        jLabel37.setText("套装4装备：");

        套装4装备.setColumns(20);
        套装4装备.setLineWrap(true);
        套装4装备.setRows(5);
        jScrollPane7.setViewportView(套装4装备);

        jLabel38.setText("伤害附加/百分比：");

        套装4伤害增加百分比.setText("0");
        套装4伤害增加百分比.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装4伤害增加百分比ActionPerformed(evt);
            }
        });

        套装4多穿一件增加.setText("0");
        套装4多穿一件增加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装4多穿一件增加ActionPerformed(evt);
            }
        });

        jLabel39.setText("多穿一件/百分比：");

        jLabel40.setText("套装5套装最低触发件数：");

        套装5触发件数.setText("0");
        套装5触发件数.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装5触发件数ActionPerformed(evt);
            }
        });

        jLabel41.setText("套装5装备：");

        套装5装备.setColumns(20);
        套装5装备.setLineWrap(true);
        套装5装备.setRows(5);
        jScrollPane9.setViewportView(套装5装备);

        jLabel42.setText("伤害附加/百分比：");

        套装5伤害增加百分比.setText("0");
        套装5伤害增加百分比.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装5伤害增加百分比ActionPerformed(evt);
            }
        });

        套装5多穿一件增加.setText("0");
        套装5多穿一件增加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装5多穿一件增加ActionPerformed(evt);
            }
        });

        jLabel44.setText("多穿一件/百分比：");

        jLabel47.setText("套装6套装最低触发件数：");

        套装6触发件数.setText("0");
        套装6触发件数.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装6触发件数ActionPerformed(evt);
            }
        });

        jLabel50.setText("套装6装备：");

        套装6装备.setColumns(20);
        套装6装备.setLineWrap(true);
        套装6装备.setRows(5);
        jScrollPane13.setViewportView(套装6装备);

        jLabel51.setText("伤害附加/百分比：");

        套装6伤害增加百分比.setText("0");
        套装6伤害增加百分比.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装6伤害增加百分比ActionPerformed(evt);
            }
        });

        套装6多穿一件增加.setText("0");
        套装6多穿一件增加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装6多穿一件增加ActionPerformed(evt);
            }
        });

        jLabel52.setText("多穿一件/百分比：");

        jButton17.setText("保存所有套装");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton4.setText("保存套装1加成");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("保存套装2加成");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton13.setText("保存套装3加成");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("保存套装4加成");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("保存套装5加成");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("保存套装6加成");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        套装叠加.setText("套装叠加");
        套装叠加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装叠加ActionPerformed(evt);
            }
        });

        jLabel53.setForeground(new java.awt.Color(255, 0, 0));
        jLabel53.setText("套装共存开启时，所有套装加成可以共存！ 套装共存关闭时，只能适用任意一套套装加成！");

        套装系统.setText("套装系统");
        套装系统.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                套装系统ActionPerformed(evt);
            }
        });

        jLabel55.setForeground(new java.awt.Color(255, 0, 51));
        jLabel55.setText("套装判断顺序为：穿戴判断[穿戴数量多 > 穿戴数量少] 控制台判断[套装1 > 套装6]  ");

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel47Layout.createSequentialGroup()
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addComponent(jLabel55))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(套装系统, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(套装叠加, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel47Layout.createSequentialGroup()
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel47Layout.createSequentialGroup()
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装3多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装3伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装3触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(4, 4, 4))
                                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel47Layout.createSequentialGroup()
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装1多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装1伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装1触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel47Layout.createSequentialGroup()
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装4多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装4伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装4触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel47Layout.createSequentialGroup()
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装2多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装2伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装2触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel47Layout.createSequentialGroup()
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel51)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装6伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装6触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel52)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装6多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel47Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(套装5多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton15))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel47Layout.createSequentialGroup()
                                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装5伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel47Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(套装5触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel41)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane13)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane6))))
                .addContainerGap())
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel47Layout.createSequentialGroup()
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(套装1触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(套装1伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(套装1多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel47Layout.createSequentialGroup()
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(套装2触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(套装2伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(套装2多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel47Layout.createSequentialGroup()
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(套装3触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(套装3伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(套装3多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel47Layout.createSequentialGroup()
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(套装4触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(套装4伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(套装4多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(jPanel47Layout.createSequentialGroup()
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(套装5触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(套装5伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(套装5多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel47Layout.createSequentialGroup()
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel47)
                                .addComponent(套装6触发件数, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(套装6伤害增加百分比, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(套装6多穿一件增加, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16))))
                .addGap(2, 2, 2)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel47Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel55))
                    .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(套装系统, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(套装叠加, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void 套装1触发件数ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装1触发件数ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装1触发件数ActionPerformed

    private void 套装1伤害增加百分比ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装1伤害增加百分比ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装1伤害增加百分比ActionPerformed

    private void 套装1多穿一件增加ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装1多穿一件增加ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装1多穿一件增加ActionPerformed

    private void 套装2触发件数ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装2触发件数ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装2触发件数ActionPerformed

    private void 套装2伤害增加百分比ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装2伤害增加百分比ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装2伤害增加百分比ActionPerformed

    private void 套装2多穿一件增加ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装2多穿一件增加ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装2多穿一件增加ActionPerformed

    private void 套装3触发件数ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装3触发件数ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装3触发件数ActionPerformed

    private void 套装3伤害增加百分比ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装3伤害增加百分比ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装3伤害增加百分比ActionPerformed

    private void 套装3多穿一件增加ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装3多穿一件增加ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装3多穿一件增加ActionPerformed

    private void 套装4触发件数ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装4触发件数ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装4触发件数ActionPerformed

    private void 套装4伤害增加百分比ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装4伤害增加百分比ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装4伤害增加百分比ActionPerformed

    private void 套装4多穿一件增加ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装4多穿一件增加ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装4多穿一件增加ActionPerformed

    private void 套装5触发件数ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装5触发件数ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装5触发件数ActionPerformed

    private void 套装5伤害增加百分比ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装5伤害增加百分比ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装5伤害增加百分比ActionPerformed

    private void 套装5多穿一件增加ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装5多穿一件增加ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装5多穿一件增加ActionPerformed

    private void 套装6触发件数ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装6触发件数ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装6触发件数ActionPerformed

    private void 套装6伤害增加百分比ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装6伤害增加百分比ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装6伤害增加百分比ActionPerformed

    private void 套装6多穿一件增加ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装6多穿一件增加ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_套装6多穿一件增加ActionPerformed
    private void 刷新套装1最少触发件数() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装1最少触发件数");
        套装1触发件数.setText("" + 显示 + "");
    }
    private void 刷新套装1附加百分比伤害() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装1附加百分比伤害");
        套装1伤害增加百分比.setText("" + 显示 + "");
    }
    private void 刷新套装1多穿一件附加() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装1多穿一件附加");
        套装1多穿一件增加.setText("" + 显示 + "");
    }
    private void 刷新套装2最少触发件数() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装2最少触发件数");
        套装2触发件数.setText("" + 显示 + "");
    }
    private void 刷新套装2附加百分比伤害() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装2附加百分比伤害");
        套装2伤害增加百分比.setText("" + 显示 + "");
    }
    private void 刷新套装2多穿一件附加() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装2多穿一件附加");
        套装2多穿一件增加.setText("" + 显示 + "");
    }
    private void 刷新套装3最少触发件数() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装3最少触发件数");
        套装3触发件数.setText("" + 显示 + "");
    }
    private void 刷新套装3附加百分比伤害() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装3附加百分比伤害");
        套装3伤害增加百分比.setText("" + 显示 + "");
    }
    private void 刷新套装3多穿一件附加() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装3多穿一件附加");
        套装3多穿一件增加.setText("" + 显示 + "");
    }
    private void 刷新套装4最少触发件数() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装4最少触发件数");
        套装4触发件数.setText("" + 显示 + "");
    }
    private void 刷新套装4附加百分比伤害() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装4附加百分比伤害");
        套装4伤害增加百分比.setText("" + 显示 + "");
    }
    private void 刷新套装4多穿一件附加() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装4多穿一件附加");
        套装4多穿一件增加.setText("" + 显示 + "");
    }
    private void 刷新套装5最少触发件数() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装5最少触发件数");
        套装5触发件数.setText("" + 显示 + "");
    }
    private void 刷新套装5附加百分比伤害() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装5附加百分比伤害");
        套装5伤害增加百分比.setText("" + 显示 + "");
    }
    private void 刷新套装5多穿一件附加() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装5多穿一件附加");
        套装5多穿一件增加.setText("" + 显示 + "");
    }
    private void 刷新套装6最少触发件数() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装6最少触发件数");
        套装6触发件数.setText("" + 显示 + "");
    }
    private void 刷新套装6附加百分比伤害() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装6附加百分比伤害");
        套装6伤害增加百分比.setText("" + 显示 + "");
    }
    private void 刷新套装6多穿一件附加() {
        int 显示 = HuiMS.ConfigValuesMap.get("套装6多穿一件附加");
        套装6多穿一件增加.setText("" + 显示 + "");
    }
    private void 刷新所有套装装备() {
        套装系统完善版 TZXT = new 套装系统完善版();
        套装1装备.setText("" + TZXT.get套装1() + "");
        套装2装备.setText("" + TZXT.get套装2() + "");
        套装3装备.setText("" + TZXT.get套装3() + "");
        套装4装备.setText("" + TZXT.get套装4() + "");
        套装5装备.setText("" + TZXT.get套装5() + "");
        套装6装备.setText("" + TZXT.get套装6() + "");
    }
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        try {
            //ini文件的存放位置
            String filepath = "套装系统.ini";
            //创建文件输入流
            InputStreamReader fis = new InputStreamReader(new FileInputStream(filepath), "UTF-8");//UTF-8
            //创建文件输出流
            OutputStream opt = null;
            //创建Properties属性对象用来接收ini文件中的属性
            Properties pps = new Properties();
            //从文件流中加载属性
            pps.load(fis);
            //通过getProperty("属性名")获取key对应的值
            //System.out.println(pps.getProperty("套装1"));
            //System.out.println(pps.getProperty("套装2"));
            //System.out.println(pps.getProperty("套装3"));
            //System.out.println(pps.getProperty("套装4"));
            //System.out.println(pps.getProperty("套装5"));
            //System.out.println(pps.getProperty("套装6"));
            //加载读取文件流
            opt = new FileOutputStream(filepath);
            //通过setProperty(key,value)赋值，会覆盖相同key的值
            if (!套装1装备.getText().equals("")) {
                pps.setProperty("TZ1", 套装1装备.getText());
            }
            if (!套装2装备.getText().equals("")) {
                pps.setProperty("TZ2", 套装2装备.getText());
            }
            if (!套装3装备.getText().equals("")) {
                pps.setProperty("TZ3", 套装3装备.getText());
            }
            if (!套装4装备.getText().equals("")) {
                pps.setProperty("TZ4", 套装4装备.getText());
            }
            if (!套装5装备.getText().equals("")) {
                pps.setProperty("TZ5", 套装5装备.getText());
            }
            if (!套装6装备.getText().equals("")) {
                pps.setProperty("TZ6", 套装6装备.getText());
            }
            //修改值 (必不可少)
            pps.store(opt, null);
            opt.close();
            HuiMS.GetConfigValues();
            刷新所有套装装备();
            JOptionPane.showMessageDialog(null, "[信息]:保存成功， 本次修改及时生效");
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("update configvalues set Val='" + this.套装1触发件数.getText() + "' where id = 41100;");
            PreparedStatement ps1 = con.prepareStatement("update configvalues set Val='" + this.套装1伤害增加百分比.getText() + "' where id = 41110;");
            PreparedStatement ps2 = con.prepareStatement("update configvalues set Val='" + this.套装1多穿一件增加.getText() + "' where id = 41111;");
            ps.executeUpdate();
            ps1.executeUpdate();
            ps2.executeUpdate();
            ps.close();
            ps1.close();
            ps2.close();
            con.close();
            HuiMS.GetConfigValues();
            刷新套装1最少触发件数();
            刷新套装1附加百分比伤害();
            刷新套装1多穿一件附加();
        } catch (SQLException ex) {
        }
        JOptionPane.showMessageDialog(null, "[信息]:保存成功， 本次修改及时生效");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("update configvalues set Val='" + this.套装2触发件数.getText() + "' where id = 42100;");
            PreparedStatement ps1 = con.prepareStatement("update configvalues set Val='" + this.套装2伤害增加百分比.getText() + "' where id = 42110;");
            PreparedStatement ps2 = con.prepareStatement("update configvalues set Val='" + this.套装2多穿一件增加.getText() + "' where id = 42111;");
            ps.executeUpdate();
            ps1.executeUpdate();
            ps2.executeUpdate();
            ps.close();
            ps1.close();
            ps2.close();
            con.close();
            HuiMS.GetConfigValues();
            刷新套装2最少触发件数();
            刷新套装2附加百分比伤害();
            刷新套装2多穿一件附加();
        } catch (SQLException ex) {
        }
        JOptionPane.showMessageDialog(null, "[信息]:保存成功， 本次修改及时生效");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("update configvalues set Val='" + this.套装3触发件数.getText() + "' where id = 43100;");
            PreparedStatement ps1 = con.prepareStatement("update configvalues set Val='" + this.套装3伤害增加百分比.getText() + "' where id = 43110;");
            PreparedStatement ps2 = con.prepareStatement("update configvalues set Val='" + this.套装3多穿一件增加.getText() + "' where id = 43111;");
            ps.executeUpdate();
            ps1.executeUpdate();
            ps2.executeUpdate();
            ps.close();
            ps1.close();
            ps2.close();
            con.close();
            HuiMS.GetConfigValues();
            刷新套装3最少触发件数();
            刷新套装3附加百分比伤害();
            刷新套装3多穿一件附加();
        } catch (SQLException ex) {
        }
        JOptionPane.showMessageDialog(null, "[信息]:保存成功， 本次修改及时生效");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("update configvalues set Val='" + this.套装4触发件数.getText() + "' where id = 44100;");
            PreparedStatement ps1 = con.prepareStatement("update configvalues set Val='" + this.套装4伤害增加百分比.getText() + "' where id = 44110;");
            PreparedStatement ps2 = con.prepareStatement("update configvalues set Val='" + this.套装4多穿一件增加.getText() + "' where id = 44111;");
            ps.executeUpdate();
            ps1.executeUpdate();
            ps2.executeUpdate();
            ps.close();
            ps1.close();
            ps2.close();
            con.close();
            HuiMS.GetConfigValues();
            刷新套装4最少触发件数();
            刷新套装4附加百分比伤害();
            刷新套装4多穿一件附加();
        } catch (SQLException ex) {
        }
        JOptionPane.showMessageDialog(null, "[信息]:保存成功， 本次修改及时生效");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("update configvalues set Val='" + this.套装5触发件数.getText() + "' where id = 45100;");
            PreparedStatement ps1 = con.prepareStatement("update configvalues set Val='" + this.套装5伤害增加百分比.getText() + "' where id = 45110;");
            PreparedStatement ps2 = con.prepareStatement("update configvalues set Val='" + this.套装5多穿一件增加.getText() + "' where id = 45111;");
            ps.executeUpdate();
            ps1.executeUpdate();
            ps2.executeUpdate();
            ps.close();
            ps1.close();
            ps2.close();
            con.close();
            HuiMS.GetConfigValues();
            刷新套装5最少触发件数();
            刷新套装5附加百分比伤害();
            刷新套装5多穿一件附加();
        } catch (SQLException ex) {
        }
        JOptionPane.showMessageDialog(null, "[信息]:保存成功， 本次修改及时生效");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("update configvalues set Val='" + this.套装6触发件数.getText() + "' where id = 46100;");
            PreparedStatement ps1 = con.prepareStatement("update configvalues set Val='" + this.套装6伤害增加百分比.getText() + "' where id = 46110;");
            PreparedStatement ps2 = con.prepareStatement("update configvalues set Val='" + this.套装6多穿一件增加.getText() + "' where id = 46111;");
            ps.executeUpdate();
            ps1.executeUpdate();
            ps2.executeUpdate();
            ps.close();
            ps1.close();
            ps2.close();
            con.close();
            HuiMS.GetConfigValues();
            刷新套装6最少触发件数();
            刷新套装6附加百分比伤害();
            刷新套装6多穿一件附加();
        } catch (SQLException ex) {
        }
        JOptionPane.showMessageDialog(null, "[信息]:保存成功， 本次修改及时生效");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void 套装叠加ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装叠加ActionPerformed
        // TODO add your handling code here:
        按键开关("套装叠加开关",40001);
        刷新套装叠加开关();
    }//GEN-LAST:event_套装叠加ActionPerformed

    private void 套装系统ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_套装系统ActionPerformed
        // TODO add your handling code here:
        按键开关("套装系统开关",41000);
        刷新套装系统开关();
    }//GEN-LAST:event_套装系统ActionPerformed
    private void 刷新套装叠加开关() {
        String 显示 = "";
        int S = HuiMS.ConfigValuesMap.get("套装叠加开关");
        if (S <= 0) {
            显示 = "套装共存:开启";
        } else {
            显示 = "套装共存:关闭";
        }
        套装叠加.setText(显示);
    }
    private void 刷新套装系统开关() {
        String 显示 = "";
        int S = HuiMS.ConfigValuesMap.get("套装系统开关");
        if (S <= 0) {
            显示 = "套装系统:开启";
        } else {
            显示 = "套装系统:关闭";
        }
        套装系统.setText(显示);
    }
    public void 按键开关(String a, int b) {
        int 检测开关 = HuiMS.ConfigValuesMap.get(a);
        PreparedStatement ps = null;
        PreparedStatement ps1 = null;
        ResultSet rs = null;
        if (检测开关 > 0) {
            try {
                ps = DatabaseConnection.getConnection().prepareStatement("UPDATE configvalues SET Val = ? WHERE id = ?");
                ps1 = DatabaseConnection.getConnection().prepareStatement("SELECT * FROM configvalues WHERE id = ?");
                ps1.setInt(1, b);
                rs = ps1.executeQuery();
                if (rs.next()) {
                    String sqlString2 = null;
                    String sqlString3 = null;
                    String sqlString4 = null;
                    sqlString2 = "update configvalues set Val= '0' where id= '" + b + "';";
                    PreparedStatement dropperid = DatabaseConnection.getConnection().prepareStatement(sqlString2);
                    dropperid.executeUpdate(sqlString2);
                }
                ps.close();
                ps1.close();
            } catch (SQLException ex) {
            }
        } else {
            try {
                ps = DatabaseConnection.getConnection().prepareStatement("UPDATE configvalues SET Val = ? WHERE id = ?");
                ps1 = DatabaseConnection.getConnection().prepareStatement("SELECT * FROM configvalues WHERE id = ?");
                ps1.setInt(1, b);
                rs = ps1.executeQuery();
                if (rs.next()) {
                    String sqlString2 = null;
                    String sqlString3 = null;
                    String sqlString4 = null;
                    sqlString2 = "update configvalues set Val= '1' where id='" + b + "';";
                    PreparedStatement dropperid = DatabaseConnection.getConnection().prepareStatement(sqlString2);
                    dropperid.executeUpdate(sqlString2);
                }
            ps.close();
            ps1.close();
            } catch (SQLException ex) {
            }
        }
        HuiMS.GetConfigValues();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(套装系统.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(套装系统.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(套装系统.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(套装系统.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new 套装系统().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField 套装1伤害增加百分比;
    private javax.swing.JTextField 套装1多穿一件增加;
    private javax.swing.JTextArea 套装1装备;
    private javax.swing.JTextField 套装1触发件数;
    private javax.swing.JTextField 套装2伤害增加百分比;
    private javax.swing.JTextField 套装2多穿一件增加;
    private javax.swing.JTextArea 套装2装备;
    private javax.swing.JTextField 套装2触发件数;
    private javax.swing.JTextField 套装3伤害增加百分比;
    private javax.swing.JTextField 套装3多穿一件增加;
    private javax.swing.JTextArea 套装3装备;
    private javax.swing.JTextField 套装3触发件数;
    private javax.swing.JTextField 套装4伤害增加百分比;
    private javax.swing.JTextField 套装4多穿一件增加;
    private javax.swing.JTextArea 套装4装备;
    private javax.swing.JTextField 套装4触发件数;
    private javax.swing.JTextField 套装5伤害增加百分比;
    private javax.swing.JTextField 套装5多穿一件增加;
    private javax.swing.JTextArea 套装5装备;
    private javax.swing.JTextField 套装5触发件数;
    private javax.swing.JTextField 套装6伤害增加百分比;
    private javax.swing.JTextField 套装6多穿一件增加;
    private javax.swing.JTextArea 套装6装备;
    private javax.swing.JTextField 套装6触发件数;
    private javax.swing.JButton 套装叠加;
    private javax.swing.JButton 套装系统;
    // End of variables declaration//GEN-END:variables
}
